### ISSUE TITLE
字典不支持枚举为Key吗

### ISSUE THREAD

**Issue by xhaoh94** [CatImmortal/CatJson#11]
/// <summary>
        /// 对比Type是否为同一类型的Type
        /// </summary>
        public static bool TypeEquals(Type t1, Type t2)
        {
#if FUCK_LUA
            t1 = CheckType(t1);
            t2 = CheckType(t2);
#endif
            return t1 == t2;
        }
这个类型判断，如果key是枚举对话，是为非intkey的，会报错

**Comment by CatImmortal** [comment]
字典key目前仅支持字符串与int，其他类型后续可能会加上

**Comment by xhaoh94** [comment]
这个功能挺常见的，加起来也不难，猫大有空补上呗。我现在是改源码的
