### ISSUE TITLE
多态序列化格式的疑问

### ISSUE THREAD

**Issue by SunHowe** [CatImmortal/CatJson#13]
![image](https://user-images.githubusercontent.com/12583154/186559110-04e7c092-f359-4762-9228-c4053804baef.png)
看到多态序列化的ToJson步骤，除了1.0版本的RealTypeKey外，额外加入了一层objectKey，实际的对象序列化文本在objectKey对应的value中。
虽然可以理解是为了做多态序列化、反序列化的流程方便，但是这样会导致对象序列化后的json文本没办法在非CatJson环境下被正确反序列化解析（例如客户端ToJson后发送给服务端）

**Comment by CatImmortal** [comment]
此处修改主要是为了能够对其序列化格式非大括号形式的对象进行多态处理，如数字类型，字符串类型，数组类型等

而且多态处理格式并非标准Json规范的内容，因此设计时不考虑跨Json库的兼容性

**Comment by CatImmortal** [comment]
此处格式修改主要是为了能够对序列化格式非大括号形式的对象进行多态处理，如数字类型，字符串类型，数组类型等

而且多态处理格式并非标准Json规范的内容，因此设计时不考虑跨Json库的兼容性

**Comment by SunHowe** [comment]
好的~感谢猫大回复，我加个开关先临时处理一下~
