### ISSUE TITLE
变量作用域问题

### ISSUE THREAD

**Issue by hia** [CatImmortal/CatJson#17]
hi 
偶然发现这个库,在测试 自定义解析器 的过程中发现一个问题,如下:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/5436139/226268022-f701c6fa-734e-4595-8121-cdbedd4fc64d.png">

在自定义反序列化时,取值需要用到 Lexer, 但是它的使用范围限定在 internal.

也就是说在反序列化时,在现有设计下是没办法取到值的.

**Comment by CatImmortal** [comment]
已修改
