### ISSUE TITLE
序列化保留

### ISSUE THREAD

**Issue by cjhxajh** [CatImmortal/CatJson#8]
对于字段/属性而言，如果其值为null,false或0，那么为了性能考虑将不会对该字段/属性进行序列化
JsonParser.ToJson 时能加个开关保留 其值为null,false或0 的字段或属性吗
某些情况下可能会用到，比如导出一些游戏设置后，我想要手动把值为false改为true的时，这个字段没了。。还得手动把字段名加上

**Comment by CatImmortal** [comment]
已经增加忽略默认值序列化的开关：JsonParser.IgnoreDefaultValue

**Comment by cjhxajh** [comment]
猫佬牛B
