### ISSUE TITLE
bool类型序列化错误

### ISSUE THREAD

**Issue by cjhxajh** [CatImmortal/CatJson#9]
public class Test
{
    public bool boolVal = true;
    public int intVal = 3;
}

Test t = new Test();
t.boolVal = false;
t.intVal = 99;
var json = CatJson.JsonParser.ToJson(t);
Debug.Log(json);
/* 输出 
{
	"intVal":99
}
*/
var lt = CatJson.JsonParser.ParseJson<Test>(json);
Debug.Log(lt.boolVal+"  " + lt.intVal);
/* 输出 
True  99
*/
上面boolVal值改成了false 反序列化时值是True

**Comment by cjhxajh** [comment]
CatJson.JsonParser.IgnoreDefaultValue = false;
禁用忽略默认值 输出是对的

另外一个问题禁用默认值 string类型必需给一个非null的值能才序列化，不然会报错

**Comment by CatImmortal** [comment]
使用最新版本V2可以通过JsonCareDefaultValue禁用被标记类型的默认值忽略
